### ISSUE TITLE
Is parallel file read from the same disk any useful?

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/sumgram#8]
Since you are reading files from an input folder, most likely the data will be stored on the same storage device. In that case attempting to read multiple files from the same storage in parallel might not be very efficient. Also, you are loading the whole file (or multiple files) in the memory for processing, which is not a scalable approach, as the program might crash on large files on machines with limited memory. If the program can work on streams like one line at a time or a block of text at a time then that would be better. Also, in that case you should be able to read from STDIN (or pipes). Take a look at https://github.com/oduwsdl/accesslog-parser for inspiration.

**Comment by anwala** [comment]
Thanks for raising these issues. 

- For reading files in parallel, you are right, from my understanding it is [detrimental to do for HDDs](https://stackoverflow.com/questions/13421767/multithread-read-from-disk) since it could mean that the read head jumps back and forth different parts of the disk, slowing down read. But this might not be the case for other architectures (e.g., SSDs) with cheaper seek times. So to account for the disparity of performance based on hardware specifics, I'm considering the --no-parallel-read (name suggestions welcome) flag to switch OFF reading files in parallel.

- I'll have to investigate further to see if there's a possibility for not reading all the files into memory at once. I believe this is the simplest implementation for generating a collection matrix; in order to get an accurate TF count, all documents have to be present. I'll have to research this issue to see if there's a scalable approach.

**Comment by anwala** [comment]
Further tests pushed me to move to sequential read by default. If a user seeks parallel read based on their architecture specifics, they may switch it on with --parallel-readtext
